
## Importamos Numpy

In [1]:
#importamos Numpy
import numpy as np
print('numpy version',np.__version__)


numpy version 1.18.1


Dimensión de una matriz, forma y como cambiarla, tamaño, tipo de dato y tamaño del tipo de dato.

In [2]:
x = np.random.randn(7)
print(type(x))
print(x)
# número de dimensiones de la estructura 
print('dimensions ',x.ndim)
# muestra las dimensiones del vector
print('shape  ',x.shape )
#devuelve el número total de elementos
print('size   ',x.size  )
#devuelve el tipo de los valores 
print('dtype    ',x.dtype  )
#devuelve el tamaño en bytes de los elementos 
print('itemsize     ',x.itemsize    ) 

<class 'numpy.ndarray'>
[ 0.19898021  1.70807196  0.21798166  0.67421772  0.59011564 -0.35970475
  1.02770696]
dimensions  1
shape   (7,)
size    7
dtype     float64
itemsize      8


## Matrices

In [3]:
#Matrices
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
rows, cols = np.shape(a)
print(a.itemsize)
print('Rows:{0:03} ; Cols:{1:03}'.format(rows,cols)) # formateamos el número.
print(a)

4
Rows:003 ; Cols:004
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Números complejos
La primera columna es la parte real, la segunda columna es la parte imaginaria. Con una matriz de dos columnas cambiando el tipo a np.complex64

In [4]:
#Números complejos
#primera columna parte real, 
#segunda columna parte imaginaria.
b = np.array([[2,3],[6,7]],dtype=np.complex64)
print(b)
comp=(2+3j) * (-1j) + (3)
print(comp)
print(type(comp))

[[2.+0.j 3.+0.j]
 [6.+0.j 7.+0.j]]
(6-2j)
<class 'complex'>


## Inicialización de Vectores

In [5]:
#Inicialización de vectores
v=np.zeros((4,5))

print('Ceros ')
print(v)
print('Identidad ')
e=np.eye(5)
print(e)
print('Complex ')
#Devuelve un array de ceros 
#con la misma forma y tipos que el dado
z=np.zeros_like(b)
print(z)

Ceros 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Identidad 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Complex 
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [6]:
# genera un ndarray desde el valor inicial al final. Uno solo se asume desde 0
a = np.arange(7) # [0..7)
print(a)
a = np.arange(7,11) #[7..11)
print(a)
dia = [1,4,2,6]
diagonal = np.diag(dia)
print( diagonal )

[0 1 2 3 4 5 6]
[ 7  8  9 10]
[[1 0 0 0]
 [0 4 0 0]
 [0 0 2 0]
 [0 0 0 6]]


Tile: La primera matriz es la matriz que queremos **tilear** (repetir) y el vector es la dimensión de la matriz resultante. En el ejemblo de abajo podemos ver como la matriz indicada se repite 2 veces en las filas y 3 en las columnas.

In [7]:
np.tile(np.array([[6,7],[8,9]]),(2,2))

array([[6, 7, 6, 7],
       [8, 9, 8, 9],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

Le cambiamos la forma al vector con reshape()

In [8]:
print(np.arange(10))
r = np.arange(9)
print(r.shape)
x = r.reshape(3,3)
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


Podemos generar matrices con alguna ecuación matemática mas sofisticada. Por ejemplo en estos ejemplos, vamos a crear una matriz en la que cada fila sea 10 veces mayor que la anterior en el primer caso y 3 veces en el segundo caso

In [9]:
c = np.array([[10*j+i for i in range(3)] for j in range(4)])
print(c)
c = np.array([[3*j+i for i in range(3)] for j in range(4)])
print(c)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
d = np.linspace(0,12,5) #genera 5 puntos entre 0 y 12 equidistantes
print(d)

#Recordad : es el operador de partición de una matriz. Se parte la matriz
#completa (:) y se añade una nueva dimensión.
#newaxis increase the dimension of the existing array by one more dimension
print(d.shape)
dp = d[np.newaxis,:]
print(dp)
print('Shape ',dp.shape)
dp = d[:,np.newaxis]
print(dp)
print('Shape ',dp.shape)

[ 0.  3.  6.  9. 12.]
(5,)
[[ 0.  3.  6.  9. 12.]]
Shape  (1, 5)
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]]
Shape  (5, 1)


Mgrid: Genera coordenadas de cuadricula. Se usa mucho en Mathlab (meshgrid)

In [11]:
#grid proviene de matlab y genera cuadriculas para dibujar en el espacio
x, y = np.mgrid[0:3,0:5]

print(x)
print("---")
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
---
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [12]:
#matrices dispersas con scipy
from scipy import sparse

X = np.random.random((5,6))
print(X)

V = X[X< 0.85]
print("filtrando")
print(V)

X[X < 0.85] = 0 # selecciona los elementos menores de 0.85 y asigna 0
print(X)

x_csr = sparse.csr_matrix(X) #CSR (Compress sparse row)

print(x_csr)

print(x_csr.toarray())


[[0.90132005 0.97744202 0.11187505 0.9522123  0.28549934 0.07337899]
 [0.26773291 0.89345607 0.13568454 0.64480259 0.6653114  0.85554909]
 [0.38708568 0.74142394 0.5141897  0.01356966 0.12284694 0.87448388]
 [0.98486811 0.3479905  0.06822674 0.05632681 0.9554474  0.60121528]
 [0.37111488 0.50294341 0.713322   0.10292338 0.77258764 0.77640412]]
filtrando
[0.11187505 0.28549934 0.07337899 0.26773291 0.13568454 0.64480259
 0.6653114  0.38708568 0.74142394 0.5141897  0.01356966 0.12284694
 0.3479905  0.06822674 0.05632681 0.60121528 0.37111488 0.50294341
 0.713322   0.10292338 0.77258764 0.77640412]
[[0.90132005 0.97744202 0.         0.9522123  0.         0.        ]
 [0.         0.89345607 0.         0.         0.         0.85554909]
 [0.         0.         0.         0.         0.         0.87448388]
 [0.98486811 0.         0.         0.         0.9554474  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
  (0, 0)	0.9013200500108589
  (0, 1)	0.977442021667

**Broadcasting**  NumPy distribuye el vector de menor dimensión sobre el largo para conseguir 
dimensiones compatibles. No siempre esp osible hacerlo, las dimensiones deben ser compatibles.

In [13]:
#broadcasting
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
c = a*b
print(c)

print("--------")

a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0]) # no se debería poder sumar, ya que las dimensiones no son iguales. en este caso 
# Numpy lo que hace es aplicar b sobre a tantas veces como filas hay.
c = a + b
print(c)

[2. 4. 6.]
--------
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [14]:
#Otras operaciones interesantes
np.random.seed(12345) # determina una semilla de números eleatorios.
r=np.random.rand(4)
print(r)
rint=r.astype(int)  #cambia el tipo
print(rint)
print(np.round(r)) # redondea ( >= 0.5)

[0.92961609 0.31637555 0.18391881 0.20456028]
[0 0 0 0]
[1. 0. 0. 0.]


In [15]:
x=np.random.rand(2,2)
print(x) 
print(x.T) #Traspuesta
print(x*5) # producto por un escalar
print(x+3) # suma a todos los elementos de la matriz
print(x*x.T) # producto de la matriz por su traspuesta
print(np.dot(x,x.T))  # producto vectorial

[[0.56772503 0.5955447 ]
 [0.96451452 0.6531771 ]]
[[0.56772503 0.96451452]
 [0.5955447  0.6531771 ]]
[[2.83862515 2.97772351]
 [4.8225726  3.26588548]]
[[3.56772503 3.5955447 ]
 [3.96451452 3.6531771 ]]
[[0.32231171 0.57441151]
 [0.57441151 0.42664032]]
[[0.6769852  0.93657519]
 [0.93657519 1.35692858]]


In [16]:
#Determinante
from scipy import linalg
arr = np.array([[1,2],[3,4]])
linalg.det(arr)

-2.0

In [17]:
#matriz inversa
linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
#accediendo a los datos de la matriz
b = np.random.random((5,6))
b = np.round(b*10)
print(b)
print(b[0,0])
print(b[-2,-2]) # de forma inversa
print(b[:,1]) # todas las filas de la segunda columna
print("-----")
print(b[0,1:3]) #la primera fila de las columnas 2 y 3
print("-----")
print(b[2::2,::5]) # patron A:B:C => A inicio, B final, C salto
# seleccionada de dos en dos desde tercera fila y selecciona desde la 
# primera columna hasta el final de 2 en 2

[[ 7.  7.  7. 10.  0.  1.]
 [ 3.  7.  8.  9. 10.  7.]
 [ 6.  7.  5.  3.  4.  7.]
 [10.  7.  8.  2.  0.  8.]
 [ 9.  0.  5.  5.  6.  1.]]
7.0
0.0
[7. 7. 7. 7. 0.]
-----
[7. 7.]
-----
[[6. 7.]
 [9. 1.]]
