# Numpy y Pandas

Pandas es el acrónimo de (Python Data Analysis Library) es un codigo fuente open source con licencia BSD que proporciona estructuras de datos, herramientas de análisis en python, fáciles de usar y de alto rendimiento.

Para importar pandas hacemos lo siguiente:

In [1]:
import pandas as pd
import numpy as np

Una **serie** en Pandas es un vector unidimensional con un índice que puede especificarse o no.

In [2]:
s = pd.Series([1,2,5,np.nan,6,8])
print(s)


0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


Un **DataFrame** son estructuras bidimensionales donde las columnas está etiquetadas con su valor y pueden ser de tipos distintos. Una analogía a un Dataframe podria ser una hoja de cálculo Excel o una tabla de una base de datos.

De forma opcional un Dataframe puede tener un ínidce. Ese ínidce será el nombre de las filas.

In [3]:
#date_range genera una lista de fechas.
dates = pd.date_range('20130101',periods=6)
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [4]:
#index=> es el índice y indica el nombre de cada fila. en este caso metemos
#el array de dates del paso anterior. Columns identifica la etiqueta de las
#columnas.

df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print(df)
display(df)

                   A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809


A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

In [5]:
#También lo podemos imprimir más bonito (solamente en Jupyter)
display(df)

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

Los tipos de datos de un dataframe pueden ser diferentes. Es la misma idea que una tabla de la base de datos. Cada columna puede ser de un tipo diferente.

In [6]:
serie = pd.Series(42,index=list(range(4)))
display(serie)
df2 = pd.DataFrame({'A':1.0,
                    'B':pd.Timestamp('20130102'),
                    'C':serie,
                    'D':2,
                    'E':pd.Categorical(['test','train','test','train']),
                    'F': "foo" 
                   })
display(df2)
print(df2.dtypes)

0    42
1    42
2    42
3    42
dtype: int64

A          B   C  D      E    F
0  1.0 2013-01-02  42  2   test  foo
1  1.0 2013-01-02  42  2  train  foo
2  1.0 2013-01-02  42  2   test  foo
3  1.0 2013-01-02  42  2  train  foo

A           float64
B    datetime64[ns]
C             int64
D             int64
E          category
F            object
dtype: object


Veamos algunas cuestiones:
* pd.Timestamp(): genera una campo de tipo timestamp.
* pd.Series Genera una serie de números. El index es el índice de la serie que es de tipo entero. Range genera los 4 primeros números.
* pd.Categorical() genera una lista de categorías.

¿Y qué pasaría si alguna de las dimensiones no encaja?

A continuación se muestran diversas funciones útiles para acceder a las 
características de un DataFrame


In [7]:
print(df.index)
print('----------------------------------------')
print(df.columns)
print('----------------------------------------')
print(df.values)
print('----------------------------------------')
display(df)
print("=========================================")
print(df.describe())

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
----------------------------------------
Index(['A', 'B', 'C', 'D'], dtype='object')
----------------------------------------
[[ 1.25379374  0.85752912 -1.59528914 -0.07925544]
 [ 0.37960247  2.52924078  0.53017371 -0.74771211]
 [ 0.91462611 -0.91992657  0.17405575  0.11483537]
 [ 1.15763155 -0.21815152  0.29648021 -0.72558392]
 [-0.22810499  1.24700648  0.905614   -0.98347177]
 [ 1.98825654 -2.45416763 -1.5340473   0.157809  ]]
----------------------------------------


A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.910968  0.173588 -0.203835 -0.377230
std    0.764038  1.756328  1.083363  0.498662
min   -0.228105 -2.454168 -1.595289 -0.983472
25%    0.513358 -0.744483 -1.107022 -0.742180
50%    1.036129  0.319689  0.235268 -0.402420
75%    1.229753  1.149637  0.471750  0.066313
max    1.988257  2.529241  0.905614  0.157809


In [8]:
#dataframe traspuesto
display(df.T)

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.253794    0.379602    0.914626    1.157632   -0.228105    1.988257
B    0.857529    2.529241   -0.919927   -0.218152    1.247006   -2.454168
C   -1.595289    0.530174    0.174056    0.296480    0.905614   -1.534047
D   -0.079255   -0.747712    0.114835   -0.725584   -0.983472    0.157809

## Ordenación

In [9]:
#Ordenar por índices
display(df)
display(df.sort_index(axis=0,ascending=False)) # ordena las filas (axis 0)
display(df.sort_index(axis=1,ascending=False)) # ordena las columnas (axis 1)

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

A         B         C         D
2013-01-06  1.988257 -2.454168 -1.534047  0.157809
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-01  1.253794  0.857529 -1.595289 -0.079255

D         C         B         A
2013-01-01 -0.079255 -1.595289  0.857529  1.253794
2013-01-02 -0.747712  0.530174  2.529241  0.379602
2013-01-03  0.114835  0.174056 -0.919927  0.914626
2013-01-04 -0.725584  0.296480 -0.218152  1.157632
2013-01-05 -0.983472  0.905614  1.247006 -0.228105
2013-01-06  0.157809 -1.534047 -2.454168  1.988257

In [10]:
#Ordenar por columnas
display(df)
display(df.sort_values(by=['C'])) 
# selecciona la columna que utilizaremos como criterio de ordenación

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-06  1.988257 -2.454168 -1.534047  0.157809
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-05 -0.228105  1.247006  0.905614 -0.983472

Las funciones head y tail nos muestran los primeros y últimos elementos respectivamente. Útiles para resumir el dataframe cuanod estos son muy grandes.

In [11]:
display(df.head())
display(df.tail())

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472

A         B         C         D
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

In [12]:
display(df['A'])
display(df.A)
print("--------------------------")
display(df)
print("=====")
display(df[1:4])
print("--------------------------")
display(df['2013-01-02':'2013-01-04'])
display(df['2013-01-02':'2013-01-02'])

2013-01-01    1.253794
2013-01-02    0.379602
2013-01-03    0.914626
2013-01-04    1.157632
2013-01-05   -0.228105
2013-01-06    1.988257
Freq: D, Name: A, dtype: float64

2013-01-01    1.253794
2013-01-02    0.379602
2013-01-03    0.914626
2013-01-04    1.157632
2013-01-05   -0.228105
2013-01-06    1.988257
Freq: D, Name: A, dtype: float64

--------------------------


A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

=====


A         B         C         D
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584

--------------------------


A         B         C         D
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584

A         B         C         D
2013-01-02  0.379602  2.529241  0.530174 -0.747712

La función loc define una selección a traves de un indice. Selecciona por filas en función del indice

In [13]:
display(df)
#print(df.loc[dates[1]])
print(df.loc['2013-01-02'])
print(df.loc[:,['A','B']]) #selecciona todas las filas y las columnas A y B
print(df.loc['2013-01-01':'2013-01-02',['A','B']]) 
#selecciona las filas '2013-01-01' a '2013-01-02' y las columnas A y B

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

A    0.379602
B    2.529241
C    0.530174
D   -0.747712
Name: 2013-01-02 00:00:00, dtype: float64
                   A         B
2013-01-01  1.253794  0.857529
2013-01-02  0.379602  2.529241
2013-01-03  0.914626 -0.919927
2013-01-04  1.157632 -0.218152
2013-01-05 -0.228105  1.247006
2013-01-06  1.988257 -2.454168
                   A         B
2013-01-01  1.253794  0.857529
2013-01-02  0.379602  2.529241


iloc() es similar, pero utiliza enteros en vez de los nombres de los campos.


In [14]:
print(df.iloc[3])
print(df.iloc[0:2,0:2])

print(df.iloc[[1,2,4],[0,2,3]])

A    1.157632
B   -0.218152
C    0.296480
D   -0.725584
Name: 2013-01-04 00:00:00, dtype: float64
                   A         B
2013-01-01  1.253794  0.857529
2013-01-02  0.379602  2.529241
                   A         C         D
2013-01-02  0.379602  0.530174 -0.747712
2013-01-03  0.914626  0.174056  0.114835
2013-01-05 -0.228105  0.905614 -0.983472


Filtrado condicional: Similar a select where condition de sql. Perme consular solo los valores que cumplan con la condición.

In [15]:
display(df)
print("--- 1 ----")
display(df[df['A'] > 0])
print("--- 2 ----")
display(df[df.B > 0]) # muestra los valores de la tabla en cuya columna B su valor sea mayor que 0
print("--- 3 ----")
display(df[df > 0]) # muestra los elementos de la tabla que sean mayores que cero. El resto serán NaN

A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-05 -0.228105  1.247006  0.905614 -0.983472
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

--- 1 ----


A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-03  0.914626 -0.919927  0.174056  0.114835
2013-01-04  1.157632 -0.218152  0.296480 -0.725584
2013-01-06  1.988257 -2.454168 -1.534047  0.157809

--- 2 ----


A         B         C         D
2013-01-01  1.253794  0.857529 -1.595289 -0.079255
2013-01-02  0.379602  2.529241  0.530174 -0.747712
2013-01-05 -0.228105  1.247006  0.905614 -0.983472

--- 3 ----


A         B         C         D
2013-01-01  1.253794  0.857529       NaN       NaN
2013-01-02  0.379602  2.529241  0.530174       NaN
2013-01-03  0.914626       NaN  0.174056  0.114835
2013-01-04  1.157632       NaN  0.296480       NaN
2013-01-05       NaN  1.247006  0.905614       NaN
2013-01-06  1.988257       NaN       NaN  0.157809

Cruzado de datos (merge) similar a la que se puede hacer en BBDD con join.

In [16]:
left = pd.DataFrame({'key' : ['foo','foo2'], 'lval':[1,2]})
right = pd.DataFrame({'key' : ['foo','foo'], 'rval':[4,5]})
display(left)
display(right)
new = pd.merge(left,right,on='key', how="left") #how : forma en la que "mergeamos" con 
#una intersección o con una unión, sálo con la izquierda o sólo con la tabla de la derecha
display(new)

key  lval
0   foo     1
1  foo2     2

key  rval
0  foo     4
1  foo     5

key  lval  rval
0   foo     1   4.0
1   foo     1   5.0
2  foo2     2   NaN

Y tambien GroupBy

In [17]:
f = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
display(f)
group = f.groupby(['A','B'])
print("-------------")
display(group) # los grupos no se pueden dibujar, group está pensado para ejecutar posteriormente una acción
# por ejemplo sumar
print("-----------")
display(group.sum())

A      B         C         D
0  foo    one  1.820445  0.957872
1  bar    one -0.266387 -0.107857
2  foo    two -0.026558  1.286216
3  bar  three  2.315611 -0.279306
4  foo    two -2.031219 -0.472797
5  bar    two  0.948603  0.976941
6  foo    one  0.921710  0.605801
7  foo  three  1.754061 -0.449506

-------------


-----------


C         D
A   B                        
bar one   -0.266387 -0.107857
    three  2.315611 -0.279306
    two    0.948603  0.976941
foo one    2.742155  1.563673
    three  1.754061 -0.449506
    two   -2.057777  0.813419