# OpenCV - Irudiekin jokatzen

Opencv liburutegia sartuko dugu. Honekin batera irakurtzen diren pixel guztiak ikusteko, numpy sartuko dugu. Guztia matrize baten dagoelako. 

In [20]:
import numpy as np
import cv2

## Orokorra

Argazki batean nola idatzi edo zuzenak, laukia edota poligonoak egin ikusteko, irudi beltz bat eraikiko dugu. Horretarako numpyrekin matrize bat osatuko dugu zeroz betea.

In [21]:
black_img = np.zeros((512, 512, 3), np.uint8)

In [22]:
cv2.imshow('BELTZA',black_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Irudi horretan zuzen bat jartzeko, non hasi (0,0) kasu honetan, non bukatu (512,512), bere kolorea (255,255,255) txuria eta lodiera (5)  jarriko diogu

In [23]:
cv2.line(black_img, (0,0), (512,512), (255,255,255), 5)
cv2.imshow('BELTZA',black_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Lauki bat egiteko sistema berdina erabiliko dugu. Non hasi, non bukatu, kolorea eta lodiera aukeratuko ditugu.

In [24]:
cv2.rectangle(black_img, (0,138), (220,400), (0,255,0), 2)
cv2.imshow('BELTZA',black_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Poligono bat egiterako garaian berriz, zein puntutatik pasatuko den esan beharra dugu. Horretarako beste matrize bat egingo dugu non puntu denak zehaztuko ditugun.

In [25]:
puntuak = np.array([[60,55],[70,80],[140,80],[100,60]], np.int32)
puntuak = puntuak.reshape((-1,1,2))
cv2.polylines(black_img, [puntuak], True, (0,0,255))
cv2.imshow('BELTZA',black_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Zerbait idatzi nahi badugu honakoa egingo dugu.

In [26]:
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(black_img, 'GUK NAHI DUGUNA IDATZI', (10,500), font, 1, (255,0,0), 2, cv2.LINE_AA)
cv2.imshow('BELTZA',black_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Iruedien erabilera

Irudiak irakurtzeko ondorengo kodigoa sartuko dugu. Normalean bere ubikazioa sartu behar zaio

In [27]:
img = cv2.imread('Argazkiak\input.jpg')

Irudiak idazterako garaian non sartuko dugun esan behar diogu eta eman diogun izenari deitu

In [28]:
cv2.imwrite("Argazkiak/output_gray.jpg", img)

True

Irudiaren luzapena aldatzea nahi badugu, modu honetako zerbait beharko genuke.

In [10]:
cv2.imwrite("Argazkiak\output.png", img, [cv2.IMWRITE_PNG_COMPRESSION])

True

BGR (Blue Green Red) sistema erabiltzen da askotan. Honek esan nahi duena da urdinaren balioa 0tik 256ra balio dezake eta beste biek ere berdin. Hiru zenbakiak matrize batean sartzen dira eta hauen konbinazioekin edozein kolore sortzea dago, beraz hiru zenbakirekin kolore bat definitzen da. Ordorengo kodean ikusten da matrize bat esaterako.

In [11]:
print(img)

[[[127 137 224]
  [127 137 224]
  [127 137 225]
  ...
  [140 154 237]
  [126 131 224]
  [100  98 198]]

 [[125 138 224]
  [125 138 224]
  [125 137 225]
  ...
  [126 146 233]
  [111 126 219]
  [ 87  95 196]]

 [[122 137 223]
  [122 137 223]
  [122 136 224]
  ...
  [117 147 234]
  [102 127 221]
  [ 80 100 201]]

 ...

 [[ 56  22  87]
  [ 58  24  89]
  [ 59  25  90]
  ...
  [ 80  69 171]
  [ 77  67 173]
  [ 73  65 172]]

 [[ 56  22  87]
  [ 57  23  88]
  [ 59  25  90]
  ...
  [ 80  71 175]
  [ 79  71 178]
  [ 77  71 180]]

 [[ 55  21  86]
  [ 57  23  88]
  [ 59  25  90]
  ...
  [ 82  73 177]
  [ 80  74 181]
  [ 80  75 184]]]


Irudia ikustea nahi badugu, imshow funtzioa erabiliko dugu. Errealitatean "cv2.imshow('irudia', img)" bakarrik beharko genuke, baina kasu honetan aplikazioa blokeatzen denez erakusten dugun irudia itxi egin behar da jarraitzeko. Hori dela eta tkla bat sakatzeko zain gelditzen da sistema eta behin hau gertatzean irudi guztiak ixteko esango diogu.

In [30]:
cv2.imshow('irudia', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Koloreen espazioak garrantzitsuak dira ikusmen artifizialean, eragiketak egiterako garaian erraztasunak ematen dituzte. Honen adibide bezala konbertsio desberdinak ikusiko ditugu.

In [31]:
# Gure argazkia grisera pasatzeko
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Gure argazkia hsv formatura pasatzeko
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.imshow('GRISA',gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('HSV',hsv_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


Argazkia lausotuta jarri nahi badugu, irudiaren ondorengo parentesi arteko zenbakiak zenbat eta handiagoak izan orduan eta lausotuagoa agertuko da irudia.

In [32]:
img_gaussian = cv2.GaussianBlur(img, (19, 19), 0)
cv2.imshow('Lausotua',img_gaussian)
cv2.waitKey(0)
cv2.destroyAllWindows()

Argazkia dilatatu nahi badugu, hau da, pixel bakoitza dilatatu, dilated erabiliko da eta iterations aldagaian esango diogu zenba nahi dugun dilatatu

In [33]:
img_dilated = cv2.dilate(img, None, iterations=1)
cv2.imshow('IRAGAZKIA',img_dilated)
cv2.waitKey(0)
cv2.destroyAllWindows()

Argazkian agertuko diren koloreak limitatu nahi baditugu, limitazioa (threshold) erabiliko dugu. kasu honetan binarioa erabiliko dugu, errazena. 50 Zenbakia izango da kasu honetan filtroa egingo duena, bere balioaren gainetik dagoen edozein zenbaki txurira joango da, 255 zenbakia jarri diogulako, eta alderantziz berdina , baina beltzera.

In [34]:
ret, img_threshold = cv2.threshold(gray_img, 50, 255, cv2.THRESH_BINARY)
cv2.imshow('IRAGAZKIA',img_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
ret, img_threshold = cv2.threshold(gray_img, 50, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('IRAGAZKIA',img_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

Irudi gris bat hartu eta aurreko filtroarekin bezala egingo da lan. Baina adaptatu egingo da lausotutako filtroa erabiliaz.

In [36]:
img_adapted_threshold = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 201, 10)
cv2.imshow('IRAGAZKIA',img_adapted_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

Lausotua erabili beharrean posible da bataz-bestekoarekin egitea.

In [37]:
img_adapted_threshold = cv2.adaptiveThreshold(gray_img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 201, 10)
cv2.imshow('IRAGAZKIA',img_adapted_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

Adibide berdina egingo dugu tomate batekin

In [38]:
img = cv2.imread("Argazkiak\shapes.png")

In [39]:
img = cv2.imread("Argazkiak/tomato.jpg")
tomato_gray =cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

Irudi gris bat hartu eta aurreko filtroarekin bezala egingo da lan. Baina adaptatu egingo da lausotutako filtroa erabiliaz.

In [40]:
img_adapted_threshold = cv2.adaptiveThreshold(tomato_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 115, 10)
cv2.imshow('IRAGAZKIA',img_adapted_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

Lausotua erabili beharrean posible da bataz-bestekoarekin egitea.

In [41]:
img_adapted_threshold = cv2.adaptiveThreshold(tomato_gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV, 115, 10)
cv2.imshow('IRAGAZKIA',img_adapted_threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()